### ISSUE TITLE
CSS 实现基于页面滚动的动画

### ISSUE THREAD

**Issue by bouquetrender** [bouquetrender/front-end-yearly#19]
在网页中，滚动动画是最常见的一种交互表现形式。在以前许多滚动动画效果（例如进度条，全屏图片标题下拉收起，图片在视口内进行展开等等）都是需要 JS 参与来获取计算 DOM 位置以及添加修改对应的 CSS 属性（例如使用 IntersectionObserver API）。直到 view-timeline 实验属性的出现，配合着 animation-timeline 可以实现非常简易高效的动画，这篇文章主要讲的就是这两个实验属性以及demo展示。

## view-timeline

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/772d74c1-ce01-4176-ada3-b8dca30c69eb)

view-timeline是用于定义一个视口进度的timeline，通常定义在一个滑动容器上，也就是你想要某个元素基于当前滚动位置来做一些你想要的效果。timeline 是一个0～100%的进度，默认当元素首次进入滚动器可见视口时，时间线为 0%，当到达边缘时为 100%。

view-timeline 是 <view-timeline-name> 和 <view-timeline-axis> 值的组合。 <view-timeline-name>是用于命名timeline的自定义名称， <view-timeline-axis>是滚动轴的值。

```css
/* 可以只设置 view-timeline-name，第二个值 view-timeline-axis 可选，默认是 block */
view-timeline: --custom_name_for_timeline block;
view-timeline: --custom_name_for_timeline inline;
view-timeline: --custom_name_for_timeline y;
view-timeline: --custom_name_for_timeline x;
view-timeline: none block;
view-timeline: none inline;
view-timeline: none y;
view-timeline: none x;

view-timeline: none;
view-timeline: --custom_name_for_timeline;
```
当可滚动的页面或者元素是横向滚动时，设置view-timeline-axis: x;

## animation-timeline

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/929ab887-81ea-4bad-b5dd-c9b16078b24c)

如果想让元素加上动画，单只是追踪记录的 view-timeline 属性可做不到，必须要配合 CSS 动画一起使用。 animation-timelin 这个 CSS 属性则是指定用于控制 CSS 动画进度的时间线。animatin-timeline 的值可以使用一些 CSS 函数 scroll() 和 view()，但这会默认使用匿名的timeline，为了更加可控和代码语义，更建议使用 view-timeline 来定义自己的 timeline。

## animation-range

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/2806a596-aec2-4955-af28-04b27b7d4645)

默认情况下的动画进度，进入视口开始进度为0%，离开视口100%。如果想控制元素进入视口的开始位置和结束位置呢？例如我想进入视口的20%才开始触发动画，80%时就结束，这是 animation-range 的作用。animation-range 用于设置动画沿时间线的开始和结束位置。

```css
animation-range: normal; /* 等于 normal normal */
animation-range: 20%; /* 等于 20% normal */
animation-range: 100px; /* 等于 100px normal */

/* 单个命名的时间线范围值 */
animation-range: cover; /* 等于 cover 0% cover 100% */
animation-range: contain; /* 等于 contain 0% contain 100% */
animation-range: cover 20%; /* 等于 cover 20% cover 100% */
animation-range: contain 100px; /* 等于 contain 100px cover 100% */

/* 两个值表示范围的起点和终点 */
animation-range: normal 25%;
animation-range: 25% normal;
animation-range: 25% 50%;
animation-range: entry exit; /* 等于 entry 0% exit 100% */
animation-range: cover cover 200px; /* 等于 cover 0% cover 200px */
animation-range: entry 10% exit; /* 等于 entry 10% exit 100% */
animation-range: 10% exit 90%;
animation-range: entry 10% 90%;
```

## 属性可视化

解三个主要的属性后，下面配合着一个可视化图来进行加深理解。当目标元素在主视口外时，此时timeline的进度0%。animation-rage是默认的cover，0%开始，100%结束。

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/e9a173aa-4dc4-4dda-893b-f16a0f8fdb2c)

当目标元素在视口内：

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/dc73feb7-deb0-4ba0-b82b-a3e57640a210)

视口外：

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/8804cefc-721c-431e-9f3c-d62c09df577e)

很清晰的看到，当0%时是元素刚进入到视口，100%则是完全离开视口。这里的百分比就是 timeline 的进度。容器的背景填充是按照着timeline的进度来。

##  实践

清晰了解了主要的流程后，接下来看基于这几个属性来实现的动画效果。建议访问每个例子的查看链接去操作感受下。

### 阅读进度条

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/0c966db9-d6d6-41d9-8be3-489842c774f2)

点击查看：https://stackblitz.com/edit/scrolldemo1?file=index.html

这是一个最基本的应用，当做一个基础的进度条时，我需要得知滚动位置，得益于view-timeline，我就可以直接配合animation-timeline做出这样随着滚动位置的效果。

```css
@keyframes progress-kf {
  from {
    transform: scaleX(0);
  }

  to {
    transform: scaleX(1);
  }
}

#progress {
  position: fixed;
  z-index: 10;
  left: 0;
  top: 0;
  width: 100%;
  height: 10px;
  transform-origin: 0 50%;
  background: #bf92bc;
}
#progress {
  animation: progress-kf auto linear;
  animation-timeline: --page-scroll;
}

html {
  width: 700px;
  margin: 0 auto;
  scroll-timeline: --page-scroll;
}
```

这里通过给 html 添加一个 scroll-timeline，并自定义命名为--page-scroll。progress 设置 animation-timeline: --page-scroll 就可以捕捉到html的滚动位置，并通过这个滚动进度来决定 animation 的当前进度。

### 文章全屏图片标题

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/418e799f-726a-48c3-bdaa-3ab133915464)

点击查看：https://stackblitz.com/edit/scrolldemo2?file=index.html
当滚动条在顶部时，图片是占满全屏，通过滚动位置来减少图片容器高度，再加上一些过渡动画，实现快速且效果不错。

```css
html {
  margin: 0 auto;
  scroll-timeline: --page-scroll;
}

.sticky-image-header {
  position: fixed;
  top: 0;

  animation: sticky-parallax-header-move-and-size linear forwards;
  animation-timeline: --page-scroll;
  animation-range: 0vh 90vh;
}

@keyframes sticky-parallax-header-move-and-size {
  from {
    background-position: 50% 0;
  }
  to {
    background-position: 50% 100%;
    background-color: #0b1584;
    height: 10vh;
    font-size: 2em;
    opacity: 0.9;
    color: black;
  }
}
```

### 堆叠卡片效果

这个效果主要是和 sticky 布局配合，当往下滑动时卡片会呈现堆叠效果

点击查看：https://stackblitz.com/edit/scrolldemo3?file=styles.css

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/118a42fd-d37b-43d7-abb8-1f07140cca21)

主要关注的结构是：

```html
<ul id="cards">
  <li class="card-li" id="card_1">
    <div class="card-content">
    </div>
  </li>

  <li class="card-li" id="card_1">
    <div class="card-content">
    </div>
  </li>
</ul>
```

最外层的 ul 设置了 grid 布局，并且设置了一个自定义 timeline 名为  --my-cards-timeline。ul 内的所有 li 元素都设置了一个 --index 标识变量，因为不依赖任何JS代码完成，所以需要用 CSS 变量标识，接下来会看到 index 的作用：

```css
#cards {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: repeat(4, 50vh);
  gap: 4vw;
  list-style: none;
  padding-bottom: 4rem;

  --numcards: 4
  view-timeline-name: --my-cards-timeline;
  padding-bottom: 10rem;
}

#card_1 {
  --index: 1;
}
#card_2 {
  --index: 2;
}
#card_3 {
  --index: 3;
}
#card_4 {
  --index: 4;
}
```

li 元素设置 sticky 粘性布局，为了将堆叠区域固定在顶部，如果去掉 sticky 布局，就可以明显看到离开动画的触发是在顶部边缘。这里还有两个关键的自定义变量 --card-original-index 和 --card-reverse-index，这两个值都用于计算用。
--card-original-index：每个 card 的索引
--card-reverse-index： 每个 card 的反向索引

```css
.card-li {
  position: sticky;
  top: 0;
  padding-top: calc(var(--index) * 1rem);

  --card-original-index: calc(var(--index) - 1);
  --card-reverse-index: calc(var(--numcards) - var(--card-original-index));
}
```

接下来看 li 元素内部的 card-li div元素，这是我们需要设置动画的元素：

```css
.card-content {
  --start-range: calc(var(--card-original-index) / var(--numcards) * 100%);
  --end-range: calc((var(--index)) / var(--numcards) * 100%);

  animation: linear scale forwards;
  animation-timeline: --my-cards-timeline;
  animation-range: exit-crossing var(--start-range) exit-crossing var(--end-range);
}

@keyframes scale {
  to {
    transform: scale(calc(1.1 - calc(0.1 * var(--card-reverse-index))));
  }
}
```

这里指定 animation-timeline 为我在 #cards 定义的 --my-cards-timeline

animation-range 的 exit-crossing 属性值是从元素首次开始穿过滚动结束边缘（0% ）到完全穿过滚动端口的结束边缘（100%）的点。--start-range 和 --end-range 是定义了动画的起始和结束范围的变量，用于每个 card 的 exit-crossing 的位置调整，这就是为什么我需要在 card-li 里去定义那两个变量 --card-original-index 和 --card-reverse-index。

定义的 scale 是将元素缩小的缩放动画，根据卡片的反向索引来计算缩放比例，使每个卡片在滚动时会有递进的缩放效果。卡片的反向索引越大，缩放比例越小：
- 如果 --card-reverse-index 是 0，缩放比例是 1.1
- 如果 --card-reverse-index 是 1，缩放比例是 1.0
- 如果 --card-reverse-index 是 2，缩放比例是 0.9
- 如果 --card-reverse-index 是 3，缩放比例是 0.8
虽然可以直接在每个card里定义1.1到0.8，但如果我需要调整缩放比例，缩放间隔0.2，不可能一个个去修改调整，计算的灵活性始终高于固定值

这样当 timeline 动画到100%结束位置时看到的效果就是：

![image](https://github.com/bouquetrender/front-end-yearly/assets/16361069/6c15fbee-b924-4f43-8d05-d0b418d8bfbf)

### 垂直滚动中的水平滚动

点击查看：https://stackblitz.com/edit/scrolldemo4?file=styles.css

根据垂直滚动的方式去进行水平滚动效果，再配合一些过渡动画。主要关注的结构是：
```html
<!-- 最外层容器 -->
<div class="container-pin bg2">
  <!-- sticky 定位 -->
  <div class="pin-sticky">
    <!-- 主要滚动部分 -->
    <div class="pin-wrap">
      <div class="content">
        Horizontal Scroll Horizontal Scroll Horizontal Scroll Horizontal
        Horizontal Scroll Horizontal Scroll Horizontal Scroll Horizontal
      </div>
    </div>
  </div>
</div>
```

首先看外层 container-pin，与顶部和底部两个 container 区别是高度设置成了 500vh，这个元素负责的就是让页面保持一个足够高的空间让页面可以垂直滚动。基于这个垂直滚动，定义view-timeline，再去做内部水平滚动的效果：

```css
.container-pin {
  height: 500vh;
  overflow: visible;

  view-timeline-name: --pin-tl;
  view-timeline-axis: block;
}
```

.pin-sticky 元素负责将需要水平滚动的这个部分设置为 sticky 定位，目的是将 .pin-wrap 元素显示在屏幕内：
```css
.pin-sticky {
  height: 100vh;
  width: 100vw;
  position: sticky;
  top: 0;

  width: 100vw;
  overflow-x: hidden;
}
```

.pin-wrap 来根据 view-timeline 执行动画进行 translateX 位移来呈现出水平滚动效果：
```css
.pin-wrap {
  height: 100vh;
  width: 280vmax;
  font-size: 6em;
  color: #8ea4b3;
  display: flex;
  align-items: center;

  will-change: transform;
  animation: linear move forwards;
  animation-timeline: --pin-tl;
  animation-range: contain 0% contain 100%;
}

@keyframes move {
  to {
    transform: translateX(calc(-100% + 100vw));
    color: #111;
    background-color: #bcb8ad;
  }
}
```

用 vmax 单位来决定水平滚动的距离可以更好的自适应。这里还需要解释一下translateX的值：calc(-100% + 100vw)
- -100% 表示将元素在 X 轴方向上向左移动其自身宽度的 100%
- 100vw 表示视口宽度的 100%

需要加上视口宽度100%的原因：如果完全移动向左100%宽度的话，整个.pin-wrap就会到移出视口外，所以需要加上视口宽度来保留。

## 总结

经过这几个实践案例，可以看到这三个属性和 animation 组合起来是可以实现十分常用的动画效果，目前除了基于 Chromium 的浏览器支持这些实验属性外，safari 和火狐也在支持计划内。
